### PR TITLE
Fix link to latency sheet

### PR DESCRIPTION
**Pull request by henrebotha**

### CODE REVIEW

**Comment by InfraredAces** [comment]
Changing the [README here](https://github.com/OpenStickCommunity/Site/blob/main/README.md) is not going to have any affect as this README is generated from the [README in the firmware repo](https://github.com/OpenStickCommunity/GP2040-CE).

**Comment by henrebotha** [comment]
Ah okay I didn't realise! I'll see about upstreaming the change.

**Comment by arntsonl** [comment]
Oh yeah anything to README.md will need to go to our other repo. I'm thinking about changing this as its pretty confusing

**Comment by henrebotha** [comment]
Should I upstream this?

**Pull request closed without merging**
